name: 10 - Build pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:

    # Use the latest Ubuntu environment for the job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Set up JDK 21 using the Microsoft distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Set up Gradle, with caching for dependencies
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      # Build the Java (Spring Boot) application using the Gradle wrapper
      - name: Build with Gradle Wrapper
        run: |
          pwd
          chmod 755 ./gradlew
          ls -ltra
          ./gradlew build
          mkdir candidate-binary && cp build/libs/*.jar candidate-binary
      - uses: actions/upload-artifact@v4
        with:
          name: Application-Binary
          path: candidate-binary

