name: 40 - Aqua Trivy Scan Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
      security-events: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x Demo/gradlew

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Change to Demo directory
        run: cd Demo && ls -l

      - name: Build the JAR file
        run: cd Demo && ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Demo
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gitactiondemo:latest

      
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Check if Trivy is installed
        run: |
          which trivy || echo "Trivy is not installed"
          trivy --version || echo "Trivy version not found"

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: trivy-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            trivy-${{ runner.os }}-

     
      - name: Scan Docker image with Trivy and generate SARIF
        run: |
          trivy image \
            --format sarif \
            --output trivy-results.sarif \
            --severity HIGH,CRITICAL \
            ghcr.io/${{ github.repository_owner }}/gitactiondemo:latest

     
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif
          category: Trivy Scan

      - name: Upload Trivy SARIF report as artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: trivy-sarif-report
          path: trivy-results.sarif
          retention-days: 30

    
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-results
          path: trivy-report.html
          retention-days: 30
