name: 00 - Main CI / CD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  docker:
    needs: build
    name: Build docker image
    uses: ./.github/workflows/docker.yml
    secrets: inherit
  container-image-scan:
    needs: docker
    name: Build docker image
    uses: ./.github/workflows/container-image-scan.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}
